Update to 1.19.4 and fix #7
ruvaldak/Semitranslucency pull request #9
Opened 2023-05-31 23:33 UTC by embeddedt

The issue was likely related to there now being two `drawTexturedQuad` methods.

Fixes #7

2023-06-01 17:27 UTC, ruvaldak commented
thanks. Sorry I haven't done this. Been out of touch of minecraft lately.

2023-06-02 16:26 UTC, hackernoodle commented
#7 is not fixed

2023-06-02 17:03 UTC, embeddedt commented
Have you tested by building this PR? The original reporter of #7 confirmed it was resolved for them.

2023-06-02 19:34 UTC, ruvaldak commented
> #7 is not fixed

I haven't merged & published this as a release yet. I was going to test it ingame yesterday but forgot.

2023-06-03 05:04 UTC, hackernoodle commented
> Have you tested by building this PR? The original reporter of #7 confirmed it was resolved for them.

I tested the build artifact from the CI run

2023-06-03 09:18 UTC, ruvaldak commented
#7 definitely isn't fixed with this. Just tested it on its own on my machine and the world still doesn't render

2023-06-03 09:25 UTC, ruvaldak requested changes
#7 still occurs. Will merge once fixed.

2023-06-03 15:25 UTC, embeddedt commented
What resource packs are being used to test this?

2023-06-03 15:47 UTC, hackernoodle commented
> What resource packs are being used to test this?

bug occurs even with no resource pack applied, i also tried https://modrinth.com/resourcepack/aquahud-flat

2023-06-03 16:17 UTC, embeddedt commented
Apparently this problem occurs only when the default vignette is enabled, Mojang must have changed something about vignette rendering that is not compatible with turning blend on.

2023-06-03 20:15 UTC, ruvaldak commented
> Apparently this problem occurs only when the default vignette is enabled, Mojang must have changed something about vignette rendering that is not compatible with turning blend on.

This will need to be fixed somehow before I publish any update. I'll keep this PR open until we can find a fix for that. Unfortunately, the code in this mod is beyond my conventional knowledge.

2023-06-04 16:25 UTC, ruvaldak commented
I'm going to go ahead and merge this, even with the vignette issue. I'm working on a 2.0 update that will simplify modloader compatibility through Architectury, so I'm going to go ahead and use the code from this PR.

2023-06-04 16:25 UTC, ruvaldak approved these changes

2023-06-04 16:25 UTC, merged